version: "3"
services:
  angular-service: # The name of the service
    container_name: app  # Container name
    build: . # Location of our Dockerfile
    ports:
      - '8000:4200' # Port mapping
    volumes:
      - "/app/node_modules"
      - ".:/app"
